name: Node.js CI

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      SENSOR_LOCATION: ${{ secrets.SENSOR_LOCATION }}
      PURPLE_AIR_API_KEY: ${{ secrets.PURPLE_AIR_API_KEY }}
      SANITY_DATA_SET: ${{ secrets.SANITY_DATA_SET }}
      SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      OPENWEATHER_MAP_API_KEY: ${{ secrets.OPENWEATHER_MAP_API_KEY }}
      ZIP_CODE: ${{ secrets.ZIP_CODE }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Execute Unit Tests
        run: |
          npm ci
          npm run test:unit